# Generated by Django 5.2.12 on 2026-04-02 17:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('metric', models.CharField(choices=[('WIN_RATE', 'Win Rate (%)'), ('AVG_RR', 'Avg Risk/Reward'), ('MAX_DRAWDOWN', 'Max Drawdown ($)'), ('TOTAL_PNL', 'Total P&L ($)'), ('TRADE_COUNT', 'Trade Count')], max_length=20)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('period', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], max_length=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACHIEVED', 'Achieved'), ('MISSED', 'Missed')], default='ACTIVE', max_length=10)),
            ],
            options={
                'ordering': ['end_date', 'status'],
            },
        ),
        migrations.CreateModel(
            name='PreTradeChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('items', models.JSONField(default=list, help_text='List of {id, label, category} dicts')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TradingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('market_open_notes', models.TextField(blank=True)),
                ('psychological_state', models.IntegerField(default=3, help_text='1 (worst) – 5 (best) mental state before trading')),
                ('psychological_notes', models.TextField(blank=True)),
                ('market_bias', models.CharField(choices=[('BULLISH', 'Bullish'), ('BEARISH', 'Bearish'), ('NEUTRAL', 'Neutral')], default='NEUTRAL', max_length=10)),
                ('vix_level', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pre_trade_checklist', models.JSONField(default=dict, help_text='Snapshot of checklist completion state for this day ({item_id: bool})')),
                ('session_notes', models.TextField(blank=True, help_text='Post-session reflections')),
                ('lessons_learned', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('symbol', models.CharField(default='SPX', max_length=10)),
                ('option_type', models.CharField(choices=[('CALL', 'Call'), ('PUT', 'Put')], max_length=4)),
                ('strike', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry', models.DateField()),
                ('quantity', models.IntegerField()),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('entry_time', models.TimeField()),
                ('exit_time', models.TimeField(blank=True, null=True)),
                ('trade_type', models.CharField(choices=[('LONG_CALL', 'Long Call'), ('LONG_PUT', 'Long Put'), ('CSP', 'Cash-Secured Put'), ('CC', 'Covered Call')], max_length=12)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('EXPIRED', 'Expired')], default='OPEN', max_length=10)),
                ('pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pnl_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('delta_entry', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('theta_entry', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('vega_entry', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('iv_entry', models.DecimalField(blank=True, decimal_places=4, help_text='Implied Volatility at entry (decimal, e.g. 0.25 = 25%)', max_digits=8, null=True)),
                ('planned_stop_loss', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('planned_take_profit_1', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('planned_take_profit_2', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('planned_take_profit_3', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('risk_reward_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('strategy_tags', models.JSONField(default=list, help_text='e.g. ["momentum", "VWAP reclaim"]')),
                ('setup_quality', models.IntegerField(blank=True, help_text='1 (poor) – 5 (excellent) self-rating at entry', null=True)),
                ('trade_notes', models.TextField(blank=True, help_text='Pre-trade rationale')),
                ('exit_notes', models.TextField(blank=True, help_text='Post-exit commentary')),
                ('ibkr_trade_id', models.CharField(blank=True, help_text='IBKR TradeID for deduplication on CSV import', max_length=64, null=True, unique=True)),
                ('imported', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='journal.tradingsession')),
            ],
            options={
                'ordering': ['-trade_date', '-entry_time'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Markdown supported')),
                ('entry_type', models.CharField(choices=[('OBSERVATION', 'Observation'), ('LESSON', 'Lesson'), ('MARKET_NOTE', 'Market Note'), ('RULE', 'Rule')], default='OBSERVATION', max_length=15)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='journal.trade')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='journal.tradingsession')),
            ],
            options={
                'verbose_name_plural': 'Journal entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_items', models.JSONField(default=dict, help_text='{item_id: bool}')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('checklist_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.pretradechecklist')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_routine', to='journal.tradingsession')),
            ],
        ),
    ]
