# Generated by Django 5.2.12 on 2026-04-09 14:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_performancegoal_process_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='is_paper_trade',
            field=models.BooleanField(default=False, help_text='Mark as paper/simulated trade (not real money)'),
        ),
        migrations.AlterField(
            model_name='apppreferences',
            name='usd_to_eur_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.9200'), help_text='Fetched automatically when P&L display currency is set to EUR.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='USD to EUR rate'),
        ),
    ]
