# Generated by Django 5.2.12 on 2026-04-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_add_is_paper_trade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='trade',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='trades',
            field=models.ManyToManyField(blank=True, related_name='journal_entries', to='journal.trade'),
        ),
    ]
