# Generated by Django 5.2.12 on 2026-04-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_replace_trade_fk_with_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingsession',
            name='plan_screenshot',
            field=models.ImageField(blank=True, help_text='Optional chart/screenshot to accompany the trading plan', null=True, upload_to='session_plans/'),
        ),
        migrations.AddField(
            model_name='tradingsession',
            name='trading_plan',
            field=models.TextField(blank=True),
        ),
    ]
